/*
 * ConversionPanelF2U.java
 *
 * Created on December 3, 2008, 12:11 PM
 */

package np.org.mpp.conv4.ui2;

import java.util.Arrays;

/**
 *
 * @author  j
 */
public class ConversionPanelF2U extends ConversionPanel {

    /** Creates new form ConversionPanelF2U */
    public ConversionPanelF2U() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabelInfo = new javax.swing.JLabel();
    jButtonOpenFile = new javax.swing.JButton();
    jLabelSelectedFiles = new javax.swing.JLabel();
    jButtonRunConversion = new javax.swing.JButton();

    jLabelInfo.setText("<html><body>Convert files with non-Unicode (Preeti, Kantipur ...) font to Unicode.<br><b>Note:</b> Only <a href=\"http://OpenOffice.org\">OpenOffice.org</a> (ODT) files are currently supported. <br>For other formats, you must install OpenOffice, open the files and save them in OpenOffice format.");

    jButtonOpenFile.setText("Choose file to convert...");
    jButtonOpenFile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonOpenFileActionPerformed(evt);
      }
    });

    jButtonRunConversion.setText("Do conversion");
    jButtonRunConversion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonRunConversionActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabelInfo)
          .addComponent(jButtonOpenFile)
          .addComponent(jLabelSelectedFiles)
          .addComponent(jButtonRunConversion))
        .addContainerGap(26, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabelInfo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButtonOpenFile)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabelSelectedFiles)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButtonRunConversion)
        .addContainerGap(215, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

private void jButtonOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenFileActionPerformed
// TODO add your handling code here:
  openFileSelection();
  if (inputOutputFiles.isEmpty()) {
    jLabelSelectedFiles.setText("No files selected. Pleace choose a file or dir with OpenOffice.org files");    
  } else {
    String sel = inputOutputFiles.toString();
// Selected these files: {/home/j/Dokumenter/foredrag/oopj_alle2.odp=/home/j/Dokumenter/foredrag_unicode/oopj_alle2.odp, /home/j/Dokumenter/foredrag/oopj_alle7.odp=/home/j/Dokumenter/foredrag_unicode/oopj_alle7.odp, /home/j/Dokumenter/foredrag/oopj_alle12.odp=/home/j/Dokumenter/foredrag_unicode/oopj_alle12.odp, /home/j/Dokumenter/foredrag/oopj_alle14.odp=/home/j/Dokumenter/foredrag_unicode/oopj_alle14.odp}

    sel = sel.substring(1, sel.length()-1).replaceAll(", ", "<br>").replaceAll("=", " -> ");
    jLabelSelectedFiles.setText("<html><body>You chose these files: <br>"+sel);
  }
  jButtonRunConversion.setEnabled(!inputOutputFiles.isEmpty());
}//GEN-LAST:event_jButtonOpenFileActionPerformed

private void jButtonRunConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunConversionActionPerformed
// TODO add your handling code here:
  runFileConversion();
}//GEN-LAST:event_jButtonRunConversionActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonOpenFile;
  private javax.swing.JButton jButtonRunConversion;
  private javax.swing.JLabel jLabelInfo;
  private javax.swing.JLabel jLabelSelectedFiles;
  // End of variables declaration//GEN-END:variables

}
